"""trans

Revision ID: 4c073a875eb5
Revises: 0cac75dc3caf
Create Date: 2024-11-24 05:42:39.560814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c073a875eb5'
down_revision: Union[str, None] = '0cac75dc3caf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('income_transaction', sa.Column('source', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('income_transaction', 'source')
    # ### end Alembic commands ###
