"""init2

Revision ID: a53297450b0d
Revises: 70d0010cd329
Create Date: 2024-11-23 04:24:24.711870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a53297450b0d'
down_revision: Union[str, None] = '70d0010cd329'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wallet', 'user_uuid',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint('wallet_user_uuid_fkey', 'wallet', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('wallet_user_uuid_fkey', 'wallet', 'user', ['user_uuid'], ['user_uuid'])
    op.alter_column('wallet', 'user_uuid',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
