"""lolkek

Revision ID: b9b8d40d3c50
Revises: 98e8ce3330e0
Create Date: 2024-11-24 00:47:59.189497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9b8d40d3c50'
down_revision: Union[str, None] = '98e8ce3330e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('card', 'expiration_date',
                    existing_type=sa.VARCHAR(length=255),
                    type_=sa.Date(),
                    existing_nullable=False,
                    postgresql_using='expiration_date::date')
    op.add_column('transaction', sa.Column('transaction_category', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'transaction_category')
    op.alter_column('card', 'expiration_date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###
