"""init7

Revision ID: fa8d434070ac
Revises: 2594d264bf57
Create Date: 2024-11-24 06:54:56.058325

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fa8d434070ac"
down_revision: Union[str, None] = "2594d264bf57"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "expense_transaction",
        sa.Column("transaction_uuid", sa.Uuid(), nullable=False),
        sa.Column("transaction_user", sa.Uuid(), nullable=False),
        sa.Column("category", sa.String(length=255), nullable=False),
        sa.Column("target_card", sa.String(length=255), nullable=False),
        sa.Column("source", sa.String(length=255), nullable=False),
        sa.Column("amount", sa.DECIMAL(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["target_card"],
            ["card.card_number"],
        ),
        sa.ForeignKeyConstraint(
            ["transaction_user"],
            ["bank_user.user_uuid"],
        ),
        sa.PrimaryKeyConstraint("transaction_uuid"),
    )
    op.create_index(
        op.f("ix_expense_transaction_transaction_uuid"),
        "expense_transaction",
        ["transaction_uuid"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_expense_transaction_transaction_uuid"),
        table_name="expense_transaction",
    )
    op.drop_table("expense_transaction")
    # ### end Alembic commands ###
