version: '3'

services:
  ai:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8808:8808" # REST
    volumes:
      - .:/app
    depends_on:
      - ollama
    command:
      - /bin/bash
      - -c
      - |
        source venv/bin/activate &&
        python /app/app.py
    stdin_open: true
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  ollama:
    volumes:
      - ./ollama/ollama:/root/.ollama
    image: ollama/ollama:latest
    ports:
      - 7869:11434
    environment:
      - OLLAMA_KEEP_ALIVE=24h
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  
  ollama-webui:
    image: ghcr.io/open-webui/open-webui:main
    volumes:
      - ./ollama/ollama-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - 8080:8080
    environment:
      - OLLAMA_BASE_URLS=http://host.docker.internal:7869
      - ENV=dev
      - WEBUI_AUTH=False
      - WEBUI_NAME=WebUI
      - WEBUI_URL=http://localhost:8080
      - WEBUI_SECRET_KEY=t0p-s3cr3t
    extra_hosts:
      - host.docker.internal:host-gateway

